name: Rebuild Binder
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Binder to rebuild
        run: |
          curl -L https://mybinder.org/build/gh/jgreathouse9/WBCameroonProject/HEAD
